### ISSUE TITLE
PWA模式下一些小问题

### ISSUE THREAD

**Issue by ttttmr** [rootknight/Miniflux-Theme-Reeder#1]
非常好用，感谢作者，有一些小问题

1. 底部操作栏和iOS触控条有点重叠，容易误触
2. 不知道顶部能不能跟随黑暗模式，颜色有点突出

![image](https://github.com/rootknight/Miniflux-Theme-Reeder/assets/32825326/4de16383-ce00-4881-910a-5f88c2ccee79)

**Comment by rootknight** [comment]
我用 safari 添加的pwa 状态栏会跟随暗黑模式

底部安全区域已经支持了，还需要官仓通过PR后实现 [#2548](https://github.com/miniflux/v2/pull/2548)

**Comment by ttttmr** [comment]
pwa状态栏的问题，我删掉重新添加好像就好了
